name: Deploy to EC2

on:
  push:
    branches:
      - prod
	  - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Set Permissions for Private Key
      run: |
        chmod 600 Assignment.pem

    - name: Add EC2 Host to Known Hosts
      run: |
        ssh-keyscan -H ec2-18-215-170-26.compute-1.amazonaws.com >> $HOME/.ssh/known_hosts
        ssh-keyscan -H ec2-18-205-21-72.compute-1.amazonaws.com >> $HOME/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          if [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            scp -i Assignment.pem -r . ubuntu@ec2-18-215-170-26.compute-1.amazonaws.com:/home/ubuntu/python-task
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            scp -i Assignment.pem -r . ubuntu@ec2-18-205-21-72.compute-1.amazonaws.com:/home/ubuntu/python-task
          fi
        fi
