name: Deploy to EC2

on:
  push:
    branches:
      - prod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set Permissions for Private Key
      run: |
        chmod 600 Assignment.pem
       
    - name: Configure SSH
      run: |
        mkdir -p $HOME/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > $HOME/.ssh/config

    - name: Deploy to EC2
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          if [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            ssh -i Assignment.pem ubuntu@ec2-18-215-170-26.compute-1.amazonaws.com "cd /home/ubuntu/python-task && git pull origin prod && python /home/ubuntu/python-task/main.py"
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            ssh -i Assignment.pem ubuntu@ec2-18-205-21-72.compute-1.amazonaws.com "cd /home/ubuntu/python-task && git pull origin test && python /home/ubuntu/python-task/main.py"
          fi
        fi
