name: Deploy Python Project

on:
  push:
    branches:
      - prod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Deploy to EC2
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          if [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            
            scp -i Assignment.pem -r . ubuntu@ec2-18-215-170-26.compute-1.amazonaws.com:/home/ubuntu/python-task
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
       
            scp -i Assignment.pem -r . ubuntu@ec2-18-205-21-72.compute-1.amazonaws.com:/home/ubuntu/python-task
          fi
        fi
