name: Deploy to AWS

on:
  push:
    branches:
      - prod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Deploy to AWS EC2
      run: |
        if [ ${{ github.ref }} == 'refs/heads/prod' ]; then
          ssh user@54.242.71.152 "cd /path/to/project && git pull origin prod && python main.py"
        elif [ ${{ github.ref }} == 'refs/heads/test' ]; then
          ssh user@3.88.228.72 "cd /path/to/project && git pull origin test && python main.py"
        fi
