name: Deployment

on:
  push:
    branches:
      - prod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Deploy to AWS EC2
      run: |
        if [ ${{ github.ref }} == 'refs/heads/prod' ]; then
          ssh ssh -i "Assignment.pem" ubuntu@ec2-54-242-71-152.compute-1.amazonaws.com "cd ~/python-task && git pull origin prod && python main.py"
        elif [ ${{ github.ref }} == 'refs/heads/test' ]; then
        ssh -i "Assignment.pem" ubuntu@ec2-3-88-228-72.compute-1.amazonaws.com "cd ~/python-task && git pull origin test && python main.py"
        fi
