name: Deployment

on:
  push:
    branches:
      - prod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_HOSTNAME}}
      - name: SSH into EC2
        run: >
          ssh -i ~/.ssh/private.key -tt ubuntu@ec2-54-242-71-152.compute-1.amazonaws.com
          "
            echo 'Welcome to EC2'
          "    

    - name: Deploy to AWS EC2
      run: |
        if [ ${{ github.ref }} == 'refs/heads/prod' ]; then
        ssh -i "private.key" ubuntu@ec2-54-242-71-152.compute-1.amazonaws.com "cd /home/ubuntu && git pull origin prod && python main.py"
        elif [ ${{ github.ref }} == 'refs/heads/test' ]; then
        ssh -i "private.key" ubuntu@ec2-3-88-228-72.compute-1.amazonaws.com "cd /home/ubuntu && git pull origin test && python main.py"
        fi
